---
name: Release

on:
  # the 1st condition
  workflow_run:
    # some older repositories still use master, all newer ones use main
    workflows: ["molecule"]
    branches: [main, master]
    types:
    - completed

# https://github.com/marketplace/actions/github-tag-with-semantic-versioning
# https://medium.com/@AranT/auto-tagging-and-using-semantic-versioning-with-github-actions-e40188d12cf4
# https://github.com/anothrNick/github-tag-action
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"

    # https://github.com/marketplace/actions/github-tag-with-semantic-versioning
    - name: Bump version and push tag
      uses: hennejg/github-tag-action@v4.3.1
      with:
        dry_run: true
        default_bump: patch
        tag_prefix: v
        release_branches: master,main
        create_annotated_tag: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
...
